// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/tsdf_2d.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();
void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();
void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();

class TSDF2D;

// ===================================================================

class TSDF2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.TSDF2D) */ {
 public:
  TSDF2D();
  virtual ~TSDF2D();

  TSDF2D(const TSDF2D& from);

  inline TSDF2D& operator=(const TSDF2D& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TSDF2D& default_instance();

  void Swap(TSDF2D* other);

  // implements Message ----------------------------------------------

  inline TSDF2D* New() const { return New(NULL); }

  TSDF2D* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TSDF2D& from);
  void MergeFrom(const TSDF2D& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TSDF2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float truncation_distance = 1;
  void clear_truncation_distance();
  static const int kTruncationDistanceFieldNumber = 1;
  float truncation_distance() const;
  void set_truncation_distance(float value);

  // optional float max_weight = 2;
  void clear_max_weight();
  static const int kMaxWeightFieldNumber = 2;
  float max_weight() const;
  void set_max_weight(float value);

  // repeated int32 weight_cells = 3;
  int weight_cells_size() const;
  void clear_weight_cells();
  static const int kWeightCellsFieldNumber = 3;
  ::google::protobuf::int32 weight_cells(int index) const;
  void set_weight_cells(int index, ::google::protobuf::int32 value);
  void add_weight_cells(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      weight_cells() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_weight_cells();

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.TSDF2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float truncation_distance_;
  float max_weight_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > weight_cells_;
  mutable int _weight_cells_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();
  friend void protobuf_AssignDesc_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();
  friend void protobuf_ShutdownFile_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto();

  void InitAsDefaultInstance();
  static TSDF2D* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TSDF2D

// optional float truncation_distance = 1;
inline void TSDF2D::clear_truncation_distance() {
  truncation_distance_ = 0;
}
inline float TSDF2D::truncation_distance() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDF2D.truncation_distance)
  return truncation_distance_;
}
inline void TSDF2D::set_truncation_distance(float value) {
  
  truncation_distance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDF2D.truncation_distance)
}

// optional float max_weight = 2;
inline void TSDF2D::clear_max_weight() {
  max_weight_ = 0;
}
inline float TSDF2D::max_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDF2D.max_weight)
  return max_weight_;
}
inline void TSDF2D::set_max_weight(float value) {
  
  max_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDF2D.max_weight)
}

// repeated int32 weight_cells = 3;
inline int TSDF2D::weight_cells_size() const {
  return weight_cells_.size();
}
inline void TSDF2D::clear_weight_cells() {
  weight_cells_.Clear();
}
inline ::google::protobuf::int32 TSDF2D::weight_cells(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.TSDF2D.weight_cells)
  return weight_cells_.Get(index);
}
inline void TSDF2D::set_weight_cells(int index, ::google::protobuf::int32 value) {
  weight_cells_.Set(index, value);
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.TSDF2D.weight_cells)
}
inline void TSDF2D::add_weight_cells(::google::protobuf::int32 value) {
  weight_cells_.Add(value);
  // @@protoc_insertion_point(field_add:cartographer.mapping.proto.TSDF2D.weight_cells)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
TSDF2D::weight_cells() const {
  // @@protoc_insertion_point(field_list:cartographer.mapping.proto.TSDF2D.weight_cells)
  return weight_cells_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
TSDF2D::mutable_weight_cells() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.mapping.proto.TSDF2D.weight_cells)
  return &weight_cells_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fproto_2ftsdf_5f2d_2eproto__INCLUDED
